[package]
name = "clock"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/clock.rs"
doctest = false


[dependencies]
serde.workspace = true
smallvec.workspace = true
workspace-hack.workspace = true
