[package]
description = "Shared protocol for communication between the Zed app and the zed.dev server"
edition.workspace = true
name = "proto"
version = "0.1.0"
publish.workspace = true
license = "GPL-3.0-or-later"


[lints]
workspace = true

[lib]
path = "src/proto.rs"
doctest = false

[dependencies]
anyhow.workspace = true
prost.workspace = true
serde.workspace = true

[build-dependencies]
prost-build.workspace = true
