[package]
name = "inline_completion_button"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/inline_completion_button.rs"
doctest = false

[dependencies]
anyhow.workspace = true
editor.workspace = true
fs.workspace = true
gpui.workspace = true
indoc.workspace = true
inline_completion.workspace = true
language.workspace = true
paths.workspace = true
regex.workspace = true
settings.workspace = true
telemetry.workspace = true
ui.workspace = true
workspace-hack.workspace = true
workspace.workspace = true

[dev-dependencies]
editor = { workspace = true, features = ["test-support"] }
futures.workspace = true
indoc.workspace = true
lsp = { workspace = true, features = ["test-support"] }
project = { workspace = true, features = ["test-support"] }
serde_json.workspace = true
theme = { workspace = true, features = ["test-support"] }
